### ISSUE TITLE
OOM Killed using bulk insertion

### ISSUE THREAD

**Issue by StephaneBunel** [prabhatsharma/zinc#47] opened 2021-12-15 18:00 UTC
I try to insert data (from a little file of 37M) but zinc get killed by OOM.
It eat more than 8GB before be killed by kernel.

```
oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/user.slice/user-1000.slice/user@1000.service,task=zinc,pid=129244,uid=1000
[13291.887950] Out of memory: Killed process 129244 (zinc) total-vm:12128240kB, anon-rss:11309292kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:22328kB oom_score_adj:0
[13292.196257] oom_reaper: reaped process 129244 (zinc), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB

[GIN-debug] Listening and serving HTTP on :4080
{"level":"debug","time":"2021-12-15T18:49:58+01:00","message":"auth: success"}
Killed
```

**Comment by susinths** [comment] 2021-12-15 18:02
https://github.com/prabhatsharma/zinc/issues/39

**Comment by prabhatsharma** [comment] 2021-12-16 11:46
Are you pushing the entire 37M data in a single HTTP request? How many records do you have in the file? Ideal number of records in a single batch should be 500 to 5k depending on the size of each record. You will need to experiment to find the ideal batch size for your data.

**Comment by prabhatsharma** [comment] 2021-12-18 11:04
@StephaneBunel Do you have any update on this?

**Comment by StephaneBunel** [comment] 2021-12-18 22:45
I worked on program that ingest and handle file of any size.
I treat input as a data stream that I batch.
The input file size is never a question, memory consumption is controlled and user is happy.

If I tell my boss my code is just crashing because the customer input file is "no of the good size", I'll get fired and I'II be agreed :-) As a user point of view it is just uncommon to accept a program simply crash because of that.

**Comment by prabhatsharma** [comment] 2021-12-21 12:44
LOL, Zinc is still in alpha and has many things it can't do yet. That being said, every software is built for a specific purpose. Zinc is built to ingest log data at regular intervals using log forwarders like fluentbit which periodically do bulk insertion. Accepting a 37M file is not really intended use case as of yet. 

Tell me more about your use case, for me to understand what problem you are trying to solve.

**Comment by ShawnMilo** [comment] 2021-12-21 17:20
@StephaneBunel 

Add the Go profiler by importing `net/pprof`:

```go
_ "net/http/pprof"
```

Then add this in `func main()`:

```go
go func() {
    log.Println(httpd.ListenAndServe("localhost:6060", nil))
}()
```

Then, while you're loading a large file, run this several times:

```
wget -O mem_$(date +%Y-%m-%d_%H%M%S).prof 'http://localhost:6060/debug/pprof/heap'
```

This will save profile files.

Then, run this using one of the files:

```
go tool pprof --source_path=/path/to/zinc/source filename.prof
```

Once you're in there, run this command:

```
top 20
```

You will be able to see exactly which lines of code are using the most memory.

Also, use the `o` command to see things you can configure. For example, you can sort by cumulative or flat, or change the `sample_index` to `alloc_space`.

If you do this, you will be able to easily troubleshoot the problem and probably provide a PR.

**Comment by prabhatsharma** [comment] 2022-01-02 23:18
So the issue is due to how GC in Go works and bluge is where the issue is happening. I will work with bluge authors to find a solution to this. https://github.com/blugelabs/bluge/issues/89

**Comment by prabhatsharma** [comment] 2022-01-26 12:22
https://github.com/prabhatsharma/zinc/releases/tag/v0.1.5 has implementation that reduces memory usage heavily.

**Comment by prabhatsharma** [comment] 2022-02-07 12:02
Closing as this is not a problem anymore.

**Closed by prabhatsharma** 2022-02-07 12:02 UTC
