### ISSUE TITLE
Zinc Search Console > Results table pane > only 20 records can be displayed as a maximum

### ISSUE THREAD

**Issue by luigidid** [prabhatsharma/zinc#62] opened 2022-01-02 17:33 UTC
Hello, in the meantime, thank you for the constantly evolving product. Very useful for my projects. One question though: from version 0.1.3 onwards, I don't understand how to enable the limitation of 20 "records" on the "ZincSearch" web application. Thank you. I only ever see 20 records.

**Comment by safeie** [comment] 2022-01-02 17:39
Duplicate of #19

**Comment by luigidid** [comment] 2022-01-02 17:47
> Duplicate of #19

Excuse me.

**Comment by safeie** [comment] 2022-01-02 17:50
this issue description question is same to #19 , it will reply in there. 
and check it, will add the future in next version.

**Comment by prabhatsharma** [comment] 2022-01-02 18:31
Same explanation as https://github.com/prabhatsharma/zinc/issues/19#issuecomment-1003756165

@luigidid Does this explanation help you move forward. Once you search for a term if there are more than 20 records you can go to the next page by using controls at the bottom right hand side of the table.

![image](https://user-images.githubusercontent.com/4242188/147885745-19d7f304-9a0e-4abb-865c-ce5bea92c67d.png)

**Comment by luigidid** [comment] 2022-01-02 18:41
> Same explanation as [#19 (comment)](https://github.com/prabhatsharma/zinc/issues/19#issuecomment-1003756165)
> 
> @luigidid Does this explanation help you move forward. Once you search for a term if there are more than 20 records you can go to the next page by using controls at the bottom right hand side of the table.
> 
> ![image](https://user-images.githubusercontent.com/4242188/147885745-19d7f304-9a0e-4abb-865c-ce5bea92c67d.png)

Hi, on the 0.1.3 version that I have recently installed, it does not return me anymore, as in the previous version, maximum 1000 records. The problem is on the "Zinc Console" WEB interface, in the "Search Results" panel. However, I need to be able to view the total of the records (see example in the image below). I know instead that in the rest call you have implemented pagination search. Very useful, as the deletion of single documents and entire indexes is very useful. Thank you!

![image](https://user-images.githubusercontent.com/96992511/147885875-def4fad8-ad72-4854-afcb-b65f4b6990be.png)

**Comment by prabhatsharma** [comment] 2022-01-02 23:10
This change in UI should help. @luigidid @safeie . Check "Max records to return" field. Let me know what you think. I will push it in the next release.

It is in this commit - https://github.com/prabhatsharma/zinc/commit/2e620929517d95f35e35f3118059ee8483c8aac8

![image](https://user-images.githubusercontent.com/4242188/147891819-7e7720cb-de17-452f-88b0-38efcaa7e1b9.png)

**Comment by luigidid** [comment] 2022-01-02 23:51
@prabhatsharma ok, thanks a lot. I saw the change made in the appropriate thread: https://github.com/prabhatsharma/zinc/commit/2e620929517d95f35e35f3118059ee8483c8aac8

It seems to me a good and flexible solution for now. In any case, I look forward to being able to download the new version of the SW and I will give you some feedback. I anticipate that I am currently using the simple binary running on a Virtual Machine with S.O RedHat 6.x. Thanks again.

**Comment by luigidid** [comment] 2022-01-07 18:20
@prabhatsharma Hi, when i will can see and download the new version of binary file of Zinc, that will contain the search through 'max_row' parameter? Thanks a lot for the work that you be conducted. Bye!

**Comment by prabhatsharma** [comment] 2022-01-09 22:16
@luigidid I should be able to make a release sometime this week.

**Comment by luigidid** [comment] 2022-01-09 22:34
> @luigidid I should be able to make a release sometime this week.

Thank's a lot @prabhatsharma . I am using the product with a lot of enthusiasm. ;)

**Comment by prabhatsharma** [comment] 2022-01-18 09:59
It is memory mapped.

**Comment by luigidid** [comment] 2022-01-18 11:10
> It is memory mapped.

Hi. thanks.

The problem is that in my opinion, however, it consumes too much RAM. Example: I have seen that for a few Kilobyes that are inserted in a .json (bulk ingestion), i find MegaBytes consumed proportional in RAM memory. Example: 10 Kylobytes of a single .json, become 100 Mbytes in ram +/-. 

In conclusion, it does not seem to me an optimal RAM management by Bluge. Is it possible to verify this high resource usage? 

In addition, at each RUN Ingestion, I had to schedule continuous restarts of the zinc process to limit RAM usage. If I don't do the restart, all the memory is saturated.

Bye

**Comment by prabhatsharma** [comment] 2022-01-18 13:06
It's a known problem that I am working on. What is your batch size?

**Comment by luigidid** [comment] 2022-01-18 13:48
> It's a known problem that I am working on. What is your batch size?

![image](https://user-images.githubusercontent.com/96992511/149948675-ff785572-0461-485d-a8a0-8290945117d3.png)

usually below 100 records, for a field layout:

![image](https://user-images.githubusercontent.com/96992511/149949406-3306f1de-255d-44dc-b1d3-91defb52124a.png)

**Comment by prabhatsharma** [comment] 2022-01-18 14:03
@luigidid Is it possible for you to join the slack channel at https://join.slack.com/t/zinc-nvh4832/shared_invite/zt-11r96hv2b-UwxUILuSJ1duzl_6mhJwVg . I would love to understand more on how you are using zinc the specific problems that you are facing and what is the best solution to them.

**Comment by prabhatsharma** [comment] 2022-01-26 12:20
Check the latest release https://github.com/prabhatsharma/zinc/releases/tag/v0.1.5 . It has implementation to reduce memory usage by huge margin.

**Comment by luigidid** [comment] 2022-01-26 14:38
> Check the latest release https://github.com/prabhatsharma/zinc/releases/tag/v0.1.5 . It has implementation to reduce memory usage by huge margin.

Hi, thanks for the change. I have installed the new Zinc (0.1.5) - [ process are launched in background on linux RHEL6 ]:

![image](https://user-images.githubusercontent.com/96992511/151180210-b1fb7b32-bb5c-4ca0-92a3-e761575bb7ba.png)

 and disabled the restart after each "bulk ingestion" run. 

I confirm that now the RAM usage has actually been optimized. As already said, for my prokect, I collect a ".json" file with a maximum of 500 records in each run:

![image](https://user-images.githubusercontent.com/96992511/151182282-2bc5cb40-25c1-4a59-ad04-7a8bafdc5509.png)

I take this opportunity to request the introduction in WEB-UI of a progress bar or circle bar to alert the user of the research in progress. Also I noticed that the ">" filter in the search bar does not produce the expected results.

If I have a string field, can I use the '>' operator in the "search" field?

TNX! bye

**Comment by luigidid** [comment] 2022-01-27 10:38
> This change in UI should help. @luigidid @safeie . Check "Max records to return" field. Let me know what you think. I will push it in the next release.
> 
> It is in this commit - [2e62092](https://github.com/prabhatsharma/zinc/commit/2e620929517d95f35e35f3118059ee8483c8aac8)
> 
> ![image](https://user-images.githubusercontent.com/4242188/147891819-7e7720cb-de17-452f-88b0-38efcaa7e1b9.png)

Hi @prabhatsharma , testing the search in the UI, I saw that if I insert the value of 70,000 in the new inputbox and, in the index in which I am searching, the total records is 65,000 c.ca, I see that the search limits the result to a maximum of 10,000. Can it be solved? I would like to see all 70,000 even with difficulty for browser RAM limit reasons. Thank you!

Example:
![image](https://user-images.githubusercontent.com/96992511/151339386-dfe2d44f-2962-440d-aac4-236592607899.png)

**Comment by safeie** [comment] 2022-01-27 12:22
you can set an env `MAX_RESULTS=100000` to change to default limit `10000`

**Comment by luigidid** [comment] 2022-01-27 13:10
> you can set an env `MAX_RESULTS=100000` to change to default limit `10000`

how can I do? how do I and when can I set that environment variable? thank you.

**Comment by safeie** [comment] 2022-01-27 13:16
if you run zinc as container, you can set environment by command `-e MAX_RESULTS=100000`, or in k8s you can set environment like this: 
```
env:
    - name: MAX_RESULTS
      value: 1000000
```

or you just run as a system command, you can start zinc like this:

```
MAX_RESULTS=10000 ./zinc
```

tell me if it can help you, or you can tell me what method you run zinc.

**Comment by luigidid** [comment] 2022-01-27 14:05
> if you run zinc as container, you can set environment by command `-e MAX_RESULTS=100000`, or in k8s you can set environment like this:
> 
> ```
> env:
>     - name: MAX_RESULTS
>       value: 1000000
> ```
> 
> or you just run as a system command, you can start zinc like this:
> 
> ```
> MAX_RESULTS=10000 ./zinc
> ```
> 
> tell me if it can help you, or you can tell me what method you run zinc.

Perfect! I use Zinc in linux RHEL 6.x, as a stand-alone "job" process and, in the background: 

![image](https://user-images.githubusercontent.com/96992511/151373986-3f643706-fb34-420f-ad13-e86619371074.png)

Ok, I have restart it by passing the env variable at the start of the process. Problem solved! ;) TNX!

**Comment by luigidid** [comment] 2022-01-28 15:14
Hi @prabhatsharma , since I installed the latest version of the SW, the empty @timestamp field appears in the index. Could you please check? Thank you.

![image](https://user-images.githubusercontent.com/96992511/151570980-e9319ca9-e30c-4865-b133-c59af67b3eea.png)

here the content of json bulk:

`{ "index" : { "_index" : "collectionTimeResponse28012022" } }
{ "DATA": "2022/01/28", "ORA": "16:04:12", "METHOD_NAME": "XXXXXXXXXXXX", "SESSION": "CEDFF2147AD57DEEC5494E981AD6159C", "ESITO": "OK", "A2A": "XXXXXXXXXXXX", "RESPONSE_TIME": "0.711", "ERROR": "--", "IP_CLIENT": "XXXXXXXXXXXX, XXXXXXXXXXXX", "NODE": "NODE02" }
{ "index" : { "_index" : "collectionTimeResponse28012022" } }
{ "DATA": "2022/01/28", "ORA": "16:04:15", "METHOD_NAME": "XXXXXXXXXXXX", "SESSION": "B718AA4AA2D6210830E79CFA77258AB1", "ESITO": "OK", "A2A": "XXXXXXXXXXXX", "RESPONSE_TIME": "0.961", "ERROR": "--", "IP_CLIENT": "XXXXXXXXXXXXX, XXXXXXXXXXXX", "NODE": "NODE02" }
`

**Comment by safeie** [comment] 2022-01-28 16:20
@luigidid  checked, and fixed it in pr #78

**Comment by gedw99** [comment] 2022-01-28 16:47
I raised an issue in Bluge to use another roaring golang implementation. It increases perf by about 30% and reduces memory pressure by about the same amount.

Bluge optimisation is the only way to increase zinc perf. GRPC api would also help in zinc but that’s not really fixing the core problem.

**Comment by prabhatsharma** [comment] 2022-02-07 12:01
Closing this issue.

**Closed by prabhatsharma** 2022-02-07 12:01 UTC
