### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by orestonce** [prabhatsharma/zinc#23] opened 2021-12-07 03:40 UTC
````
mkdir data
docker run -v $(pwd)/data:/data  -e DATA_PATH="/data" -p 4080:4080 -e FIRST_ADMIN_USER=admin -e FIRST_ADMIN_PASSWORD=Complexpass#123 -p 4081:4081 public.ecr.aws/m5j1b6u0/zinc:v0.1.1
````
* output:
````
WARNING: The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64) and no specific platform was requested
{"level":"debug","time":"2021-12-07T03:39:24Z","message":"Loading indexes..."}
{"level":"debug","time":"2021-12-07T03:39:24Z","message":"Loading system indexes..."}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xa299e4]

goroutine 1 [running]:
github.com/prabhatsharma/zinc/pkg/core.LoadZincSystemIndexes(0xc000402f00, 0x0, 0x0)
	/go/src/github.com/prabhatsharma/zinc/pkg/core/LoadIndexes.go:26 +0x1a4
github.com/prabhatsharma/zinc/pkg/core.init()
	/go/src/github.com/prabhatsharma/zinc/pkg/core/types.go:10 +0x3e
````

**Comment by HeCorr** [comment] 2021-12-07 06:06
Possible duplicate of #1 (although the stack looks a bit different)

**Comment by kanniget** [comment] 2021-12-07 07:24
I had the same issue, you need to change the permissions on your data directory...  I did chmod a+rwx /opt/data and it worked.

**Closed** 2021-12-07 07:53 UTC
