### ISSUE TITLE
on ubuntu bionic new version 1.7 keep CPU running

### ISSUE THREAD

**Issue by ivan-redooc** [prabhatsharma/zinc#98] opened 2022-02-21 15:52 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
On ubuntu bionic new version 1.7 keep CPU running

**Which service(s) is this relate to?**
I think is the CORE

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard or not doable?**
I think in some kind of loop trying to acquire some resource (see the following strace ).
It happens in `GIN_MODE=release` too.

**Are you currently working around this issue?**
no

**Additional context**
### Starting banner ###
```TXT
root:/opt/zinc# ./zinc
{"level":"debug","time":"2022-02-21T16:45:31+01:00","message":"Error loading .env file"}
{"level":"debug","time":"2022-02-21T16:45:31+01:00","message":"Loading system indexes..."}
{"level":"debug","time":"2022-02-21T16:45:31+01:00","message":"Index loaded: _index_mapping"}
{"level":"debug","time":"2022-02-21T16:45:31+01:00","message":"Index loaded: _index_template"}
{"level":"debug","time":"2022-02-21T16:45:31+01:00","message":"Index loaded: _metadata"}
{"level":"debug","time":"2022-02-21T16:45:31+01:00","message":"Index loaded: _users"}
{"level":"debug","time":"2022-02-21T16:45:31+01:00","message":"Loading indexes... from disk"}
{"level":"debug","time":"2022-02-21T16:45:31+01:00","message":"Loading indexes from s3..."}
{"level":"debug","time":"2022-02-21T16:45:31+01:00","message":"Loading indexes from minio..."}
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /                         --> github.com/prabhatsharma/zinc/pkg/meta/v1.GUI (4 handlers)
[GIN-debug] GET    /version                  --> github.com/prabhatsharma/zinc/pkg/meta/v1.GetVersion (4 handlers)
[GIN-debug] GET    /healthz                  --> github.com/prabhatsharma/zinc/pkg/meta/v1.GetHealthz (4 handlers)
[GIN-debug] GET    /ui/*filepath             --> github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (4 handlers)
[GIN-debug] HEAD   /ui/*filepath             --> github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (4 handlers)
[GIN-debug] POST   /api/login                --> github.com/prabhatsharma/zinc/pkg/handlers.ValidateCredentials (4 handlers)
[GIN-debug] PUT    /api/user                 --> github.com/prabhatsharma/zinc/pkg/handlers.CreateUpdateUser (5 handlers)
[GIN-debug] DELETE /api/user/:userID         --> github.com/prabhatsharma/zinc/pkg/handlers.DeleteUser (5 handlers)
[GIN-debug] GET    /api/users                --> github.com/prabhatsharma/zinc/pkg/handlers.GetUsers (5 handlers)
[GIN-debug] PUT    /api/index                --> github.com/prabhatsharma/zinc/pkg/handlers.CreateIndex (5 handlers)
[GIN-debug] GET    /api/index                --> github.com/prabhatsharma/zinc/pkg/handlers.ListIndexes (5 handlers)
[GIN-debug] DELETE /api/index/:indexName     --> github.com/prabhatsharma/zinc/pkg/handlers.DeleteIndex (5 handlers)
[GIN-debug] POST   /api/_bulk                --> github.com/prabhatsharma/zinc/pkg/handlers.BulkHandler (5 handlers)
[GIN-debug] POST   /api/:target/_bulk        --> github.com/prabhatsharma/zinc/pkg/handlers.BulkHandler (5 handlers)
[GIN-debug] PUT    /api/:target/document     --> github.com/prabhatsharma/zinc/pkg/handlers.UpdateDocument (5 handlers)
[GIN-debug] POST   /api/:target/_doc         --> github.com/prabhatsharma/zinc/pkg/handlers.UpdateDocument (5 handlers)
[GIN-debug] PUT    /api/:target/_doc/:id     --> github.com/prabhatsharma/zinc/pkg/handlers.UpdateDocument (5 handlers)
[GIN-debug] POST   /api/:target/_search      --> github.com/prabhatsharma/zinc/pkg/handlers.SearchIndex (5 handlers)
[GIN-debug] DELETE /api/:target/_doc/:id     --> github.com/prabhatsharma/zinc/pkg/handlers.DeleteDocument (5 handlers)
[GIN-debug] GET    /api/:target/_mapping     --> github.com/prabhatsharma/zinc/pkg/handlers.GetIndexMapping (5 handlers)
[GIN-debug] PUT    /api/:target/_mapping     --> github.com/prabhatsharma/zinc/pkg/handlers.UpdateIndexMapping (5 handlers)
[GIN-debug] GET    /es/                      --> github.com/prabhatsharma/zinc/pkg/routes.SetRoutes.func2 (4 handlers)
[GIN-debug] GET    /es/_license              --> github.com/prabhatsharma/zinc/pkg/routes.SetRoutes.func3 (4 handlers)
[GIN-debug] GET    /es/_xpack                --> github.com/prabhatsharma/zinc/pkg/routes.SetRoutes.func4 (4 handlers)
[GIN-debug] POST   /es/_search               --> github.com/prabhatsharma/zinc/pkg/handlers/v2.SearchIndex (5 handlers)
[GIN-debug] POST   /es/:target/_search       --> github.com/prabhatsharma/zinc/pkg/handlers/v2.SearchIndex (5 handlers)
[GIN-debug] GET    /es/_index_template       --> github.com/prabhatsharma/zinc/pkg/handlers/v2.ListIndexTemplate (5 handlers)
[GIN-debug] PUT    /es/_index_template/:target --> github.com/prabhatsharma/zinc/pkg/handlers/v2.UpdateIndexTemplate (5 handlers)
[GIN-debug] GET    /es/_index_template/:target --> github.com/prabhatsharma/zinc/pkg/handlers/v2.GetIndexTemplate (5 handlers)
[GIN-debug] HEAD   /es/_index_template/:target --> github.com/prabhatsharma/zinc/pkg/handlers/v2.GetIndexTemplate (5 handlers)
[GIN-debug] DELETE /es/_index_template/:target --> github.com/prabhatsharma/zinc/pkg/handlers/v2.DeleteIndexTemplate (5 handlers)
[GIN-debug] GET    /es/:target/_mapping      --> github.com/prabhatsharma/zinc/pkg/handlers.GetIndexMapping (5 handlers)
[GIN-debug] PUT    /es/:target/_mapping      --> github.com/prabhatsharma/zinc/pkg/handlers.UpdateIndexMapping (5 handlers)
[GIN-debug] POST   /es/:target/_doc          --> github.com/prabhatsharma/zinc/pkg/handlers.UpdateDocument (5 handlers)
[GIN-debug] PUT    /es/:target/_doc/:id      --> github.com/prabhatsharma/zinc/pkg/handlers.UpdateDocument (5 handlers)
[GIN-debug] PUT    /es/:target/_create/:id   --> github.com/prabhatsharma/zinc/pkg/handlers.UpdateDocument (5 handlers)
[GIN-debug] POST   /es/:target/_create/:id   --> github.com/prabhatsharma/zinc/pkg/handlers.UpdateDocument (5 handlers)
[GIN-debug] POST   /es/:target/_update/:id   --> github.com/prabhatsharma/zinc/pkg/handlers.UpdateDocument (5 handlers)
[GIN-debug] DELETE /es/:target/_doc/:id      --> github.com/prabhatsharma/zinc/pkg/handlers.DeleteDocument (5 handlers)
[GIN-debug] POST   /es/_bulk                 --> github.com/prabhatsharma/zinc/pkg/handlers.ESBulkHandler (5 handlers)
[GIN-debug] POST   /es/:target/_bulk         --> github.com/prabhatsharma/zinc/pkg/handlers.ESBulkHandler (5 handlers)
[GIN-debug] Listening and serving HTTP on :4080

```

### Strace of the process  - (the loop) ###
```TXT

13654 <... rt_sigreturn resumed> )      = 824634952608
13658 rt_sigreturn({mask=[]} <unfinished ...>
13657 futex(0x1e271b8, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
13658 <... rt_sigreturn resumed> )      = -1 ETIMEDOUT (Connection timed out)
13659 getpid( <unfinished ...>
13657 <... futex resumed> )             = 0
13659 <... getpid resumed> )            = 13654
13658 sched_yield( <unfinished ...>
13659 tgkill(13654, 13654, SIGURG <unfinished ...>
13658 <... sched_yield resumed> )       = 0
13654 --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=13654, si_uid=0} ---
13659 <... tgkill resumed> )            = 0
13654 rt_sigreturn({mask=[]} <unfinished ...>
13659 getpid( <unfinished ...>
13654 <... rt_sigreturn resumed> )      = 824635831328
13659 <... getpid resumed> )            = 13654
13658 futex(0x1e27098, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
13659 tgkill(13654, 13658, SIGURG <unfinished ...>
13654 getpid( <unfinished ...>
13661 <... futex resumed> )             = 0
13654 <... getpid resumed> )            = 13654
13661 futex(0x1e27098, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
13654 tgkill(13654, 13659, SIGURG <unfinished ...>
13661 <... futex resumed> )             = 0
13654 <... tgkill resumed> )            = 0
13661 futex(0xc000100550, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
13659 <... tgkill resumed> )            = 0
13664 <... futex resumed> )             = 0
13661 <... futex resumed> )             = 1
13659 --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=13654, si_uid=0} ---
13664 futex(0xc000100550, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
13661 sched_yield( <unfinished ...>
13659 rt_sigreturn({mask=[]} <unfinished ...>
13661 <... sched_yield resumed> )       = 0
13659 <... rt_sigreturn resumed> )      = 0
13654 futex(0xc000502058, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
13658 <... futex resumed> )             = 1
13654 <... futex resumed> )             = 0
13659 futex(0xc000234d50, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
13661 nanosleep({tv_sec=0, tv_nsec=3000},  <unfinished ...>
13658 --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=13654, si_uid=0} ---
13657 futex(0xc000076950, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
13658 rt_sigreturn({mask=[]} <unfinished ...>
13656 futex(0x1e27098, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
13658 <... rt_sigreturn resumed> )      = 1
13656 <... futex resumed> )             = 0
13658 futex(0x1e271b8, FUTEX_WAIT_PRIVATE, 0, {tv_sec=0, tv_nsec=100000} <unfinished ...>
13661 <... nanosleep resumed> NULL)     = 0
13656 futex(0xc000076550, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
13661 futex(0x1e271b8, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
13654 sched_yield( <unfinished ...>
13661 <... futex resumed> )             = 1
13654 <... sched_yield resumed> )       = 0
13658 <... futex resumed> )             = 0
13654 futex(0x1e27098, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
13658 futex(0x1e271b8, FUTEX_WAIT_PRIVATE, 0, {tv_sec=0, tv_nsec=100000} <unfinished ...>
13654 <... futex resumed> )             = 0
13654 futex(0xc000076550, FUTEX_WAKE_PRIVATE, 1) = 1
13656 <... futex resumed> )             = 0
13661 futex(0xc0003a2150, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
13656 futex(0x1e271b8, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
13658 <... futex resumed> )             = 0
13656 <... futex resumed> )             = 1
13654 futex(0x1e24eb0, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
13658 futex(0x1e27188, FUTEX_WAIT_PRIVATE, 0, {tv_sec=0, tv_nsec=100000} <unfinished ...>
13656 futex(0x1e27188, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
13658 <... futex resumed> )             = -1 EAGAIN (Resource temporarily unavailable)
13660 <... epoll_pwait resumed> [], 128, 1, NULL, 531980466199993) = 0
13656 <... futex resumed> )             = 0
13660 futex(0xc000235150, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
13658 sched_yield( <unfinished ...>
13656 futex(0xc000076550, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
13658 <... sched_yield resumed> )       = 0
13658 futex(0x1e27098, FUTEX_WAKE_PRIVATE, 1) = 0
13658 epoll_pwait(4, [], 128, 0, NULL, 0) = 0
13658 mmap(NULL, 262144, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f127ba2b000
13658 futex(0xc000235150, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
13660 <... futex resumed> )             = 0
13658 <... futex resumed> )             = 1
13660 sched_yield()                     = 0
13660 futex(0x1e27098, FUTEX_WAIT_PRIVATE, 2, NULL <unfinished ...>
13658 futex(0x1e27098, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
13660 <... futex resumed> )             = -1 EAGAIN (Resource temporarily unavailable)
13658 <... futex resumed> )             = 0
13660 futex(0x1e271b8, FUTEX_WAKE_PRIVATE, 1) = 0
13658 sched_yield( <unfinished ...>
13660 epoll_pwait(4,  <unfinished ...>
13658 <... sched_yield resumed> )       = 0
13660 <... epoll_pwait resumed> [], 128, 0, NULL, 0) = 0
13658 futex(0x1e27098, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
13660 futex(0xc000076550, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
13658 <... futex resumed> )             = 0
13660 <... futex resumed> )             = 1
13656 <... futex resumed> )             = 0
13660 epoll_pwait(4,  <unfinished ...>
13656 epoll_pwait(4,  <unfinished ...>
13660 <... epoll_pwait resumed> [], 128, 0, NULL, 2) = 0
13656 <... epoll_pwait resumed> [], 128, 0, NULL, 0) = 0
13660 epoll_pwait(4,  <unfinished ...>
13656 futex(0x1e24eb0, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
13660 <... epoll_pwait resumed> [], 128, 0, NULL, 2) = 0
13656 <... futex resumed> )             = 1
13654 <... futex resumed> )             = 0
13660 epoll_pwait(4,  <unfinished ...>
13654 epoll_pwait(4,  <unfinished ...>
13660 <... epoll_pwait resumed> [], 128, 0, NULL, 1) = 0
13654 <... epoll_pwait resumed> [], 128, 0, NULL, 140720462741632) = 0
13658 mmap(NULL, 262144, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0 <unfinished ...>
13654 epoll_pwait(4,  <unfinished ...>
13658 <... mmap resumed> )              = 0x7f127b9eb000
13654 <... epoll_pwait resumed> [], 128, 0, NULL, 140720462741632) = 0
13656 epoll_pwait(4,  <unfinished ...>
13654 epoll_pwait(4,  <unfinished ...>
13656 <... epoll_pwait resumed> [], 128, 0, NULL, 2) = 0
13654 <... epoll_pwait resumed> [], 128, 0, NULL, 140720462741632) = 0
13660 futex(0xc0003a2150, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
13654 epoll_pwait(4,  <unfinished ...>
13656 epoll_pwait(4,  <unfinished ...>
13655 <... nanosleep resumed> NULL)     = 0
13658 futex(0xc000100150, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
13656 <... epoll_pwait resumed> [], 128, 0, NULL, 1) = 0
13658 <... futex resumed> )             = -1 EAGAIN (Resource temporarily unavailable)
13656 madvise(0xc000600000, 2097152, MADV_NOHUGEPAGE <unfinished ...>
13655 futex(0xc000100150, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
13661 <... futex resumed> )             = 0
13660 <... futex resumed> )             = 1
13656 <... madvise resumed> )           = 0
13661 futex(0xc0003a2150, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
13658 futex(0xc000100150, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
13656 madvise(0xc00071e000, 8192, MADV_DONTNEED <unfinished ...>
13655 <... futex resumed> )             = 0
13656 <... madvise resumed> )           = 0
13660 futex(0xc000100150, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
13656 sched_yield( <unfinished ...>
13660 <... futex resumed> )             = 1

```
**Attachments**
### top ###
CPU usage ~ 150%
![image](https://user-images.githubusercontent.com/11387801/154988295-5d60f6eb-26c7-4a21-a428-9ff785b1af90.png)

**Comment by prabhatsharma** [comment] 2022-02-21 16:53
Please try v0.1.8 latest release. The issue is now fixed.

**Comment by ivan-redooc** [comment] 2022-02-21 17:06
> Please try v0.1.8 latest release. The issue is now fixed.

solved for me

**Closed** 2022-02-22 09:34 UTC
